### ISSUE TITLE
Table class inaccessible in the FrontEnd-Library

### ISSUE THREAD

**Issue by luis-espinoza-jalafund** [Pending-Name-21/frontend-library#31]
When using Keyboard from "CoffeeTime/InputEvents/Keyboard" an error occurs when using the keyboard.type() method indicating that "Table" cannot be accessed. 

![keyboardError](https://github.com/Pending-Name-21/frontend-library/assets/100800944/c84efd20-df24-4ea6-94c1-b775d41fd96e)

**Comment by zrock-dev** [comment]
Dear @LuchoVera1,

This issue is because frontend-library has
com.google.flatbuffers:flatbuffers-java:23.5.26 as a dependency and it's
not being included in the compiled version.

I'll work in this issue by including that dependency in the build of
frontend-library.

Sincerely,
@zrock-dev

**Comment by teran-joseluis** [comment]
> When using Keyboard from "CoffeeTime/InputEvents/Keyboard" an error occurs when using the keyboard.type() method indicating that "Table" cannot be accessed.
> 
> ![keyboardError](https://private-user-images.githubusercontent.com/100800944/345243980-c84efd20-df24-4ea6-94c1-b775d41fd96e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODQ2MzksIm5iZiI6MTcxOTk4NDMzOSwicGF0aCI6Ii8xMDA4MDA5NDQvMzQ1MjQzOTgwLWM4NGVmZDIwLWRmMjQtNGVhNi05NGMxLWI3NzVkNDFmZDk2ZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMDUyNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU5MDU3ZDM5YzYyMTQzNDliNGQ1ODkxYmVkZDM2NjJkMTcwMDIzMjQyNDRlNzRjZmY3NGRiY2EwMjFhYWZiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OyfI1xEpQjjADwMalZIE2fMMxeh6g-7Lv114IMYe0qM)

@LuchoVera1, the issue related to cannot be accessed was resolved in [**PR - 32**](https://github.com/Pending-Name-21/frontend-library/pull/32).

Let us know if the issue persists, otherwise, please continue working on the project.
